### PR TITLE
Server: Shows pacoapp://experiment/123456 link in Edit-Admin tab

### PR DESCRIPTION
**Pull request by mhadjimichael**
This should show the mobile shareable link in Edit->Admin tab.

Implements #1269

### CODE REVIEW

**Comment by BobEvans** [comment]
Hi Marios, Would it be easy for you to send me a screenshot of what this looks like? Best,
Bob

**Comment by mhadjimichael** [comment]
Hello,

It looks like this:
image

Thank you.

**Comment by BobEvans** [comment]
Thanks for the screenshot Marios.

I think it takes up a lot of space. Let me ping Ian, our main frontend guy and get his thought on where we can put this.

Hey Ian,

This addition adds the share link for users to be able to share paco experiments with each other and to publish the experiment id in a format that both Android and iOS can use to go straight to the join flow of a particular experiment (similar to the way qr code launching works).

Anyway, I think that having a whole row in the admin tab to expose this information is too much space. It seems like it might be better if it was a popup with an icon next to the experimentId field. Maybe a share icon or action that when clicked showed the url in a way that was copyable (maybe in an editable text field with focus).

Any thoughts on an economical way to add this information to the admin tab?

Best,
Bob

**Comment by ianspiro** [comment]
Sorry for the long delay on this!

Is this URL feature supported on the client yet? I'm trying to load such an address on my Android and it isn't working.

**Comment by BobEvans** [comment]
I believe it’s in the develop branch but not in production.

**Comment by mhadjimichael** [comment]
Yes, it's in develop.
This was the pull request: #1262

**Pull request merged**
